### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by luojianet** [chenjiahan/vant-touch-emulator#1]
selection.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at i.p.pipe.e [as project] (selection.js:1)
    at i._next (selection.js:1)
    at i.next (selection.js:1)
    at t (selection.js:1)

my project is response site,import this reposity,when use vant-ui Picker components ,receive this error message.

**Comment by chenjiahan** [comment]
Can you provide a codesandbox link to reproduce this problem?

https://codesandbox.io/s/m5v3f

**Comment by luojianet** [comment]
https://codesandbox.io/embed/vant-issue-moban-qxrhh

**Comment by luojianet** [comment]
https://youzan.github.io/vant/#/zh-CN/picker

vant-ui site have same error

**Comment by luojianet** [comment]
Error come from Chrome plugin[沙拉查词](https://chrome.google.com/webstore/detail/%E6%B2%99%E6%8B%89%E6%9F%A5%E8%AF%8D-%E8%81%9A%E5%90%88%E8%AF%8D%E5%85%B8%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91/cdonnmffkdaoajfknoeeecmchibpmkmg?hl=en)
